// <auto-generated />
using DataLayerGameOfLife;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayerGameOfLife.Migrations
{
    [DbContext(typeof(GameOfLifeContext))]
    [Migration("20260328171240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("DataLayerGameOfLife.Models.InitialState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InitialStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blinker",
                            State = "1,2;2,2;3,2;"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Block",
                            State = "1,1;1,2;2,1;2,2;"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
